#! /usr/bin/env python
# encoding: utf-8

PROJECT_NAME = 'shaderapidx11'


def options(opt):
    return


def configure(conf):
    if conf.env.DEST_OS != 'win32' or conf.env.GL:
        return

    conf.env.append_unique('DEFINES', [
        'SHADERAPIDX11',
        'SHADER_DLL_EXPORT',
        'USE_ACTUAL_DX',
        'strncpy=use_Q_strncpy_instead',
        '_snprintf=use_Q_snprintf_instead',
    ])


def build(bld):
    if bld.env.DEST_OS != 'win32' or bld.env.GL:
        return

    source = [
        '../../public/filesystem_helpers.cpp',

        # Backend-neutral/base code.
        '../shaderapidx9/meshbase.cpp',
        '../shaderapidx9/shaderdevicebase.cpp',
        '../shaderapidx9/shaderapibase.cpp',
        '../shaderapidx9/hardwareconfig.cpp',

        # DX11 implementation.
        'meshdx11.cpp',
        'shaderapidx11.cpp',
        'shaderdevicedx11.cpp',
        'shadershadowdx11.cpp',
        'inputlayoutdx11.cpp',

        '../../public/tier0/memoverride.cpp',
    ]

    includes = [
        '.',
        '../../public',
        '../../public/tier0',
        '../../public/tier1',
        '../../common',
        '../',
        '../shaderapidx9',
    ]

    libs = [
        'tier0',
        'tier1',
        'tier2',
        'vstdlib',
        'togl',
        'bitmap',
        'mathlib',
        'bzip2',
    ]

    bld.shlib(
        source=source,
        target=PROJECT_NAME,
        name=PROJECT_NAME,
        features='c cxx',
        includes=includes,
        defines=[],
        use=libs,

        # Do not rely on uselib definitions for these system libraries.
        linkflags=[
            'd3d11.lib',
            'dxgi.lib',
            'd3dcompiler.lib',
            'user32.lib',
        ],

        install_path=bld.env.LIBDIR,
        subsystem='WINDOWS',
    )