#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'materialsystem'


def options(opt):
	# stub
	return


def configure(conf):
	conf.env.append_unique('DEFINES', [
		'DEFINE_MATERIALSYSTEM_INTERFACE',
		'MATERIALSYSTEM_EXPORTS',
		'strncpy=use_Q_strncpy_instead',
		'_snprintf=use_Q_snprintf_instead'
	])


def build(bld):
	source = [
		'CColorCorrection.cpp',
		'cmaterial.cpp',
		'cmaterial_queuefriendly.cpp',
		'CMaterialSubRect.cpp',
		'cmaterialvar.cpp',
		'cmatnullrendercontext.cpp',
		'colorspace.cpp',
		'ctexture.cpp',
		'../public/filesystem_helpers.cpp',
		'imagepacker.cpp',
		'mat_stub.cpp',
		'materialsystem_global.cpp',
		'morph.cpp',
		'occlusionquerymgr.cpp',
		'shadersystem.cpp',
		'texturemanager.cpp',
		'pch_materialsystem.cpp',

		# Render backend abstraction + DX11 backend.
		'renderbackend.cpp',
		'renderbackend_d3d11.cpp',

		'cmaterialdict.cpp',
		'cmaterialsystem.cpp',
		'cmatlightmaps.cpp',
		'cmatrendercontext.cpp',
		'cmatqueuedrendercontext.cpp',
		'ctexturecompositor.cpp',

		'../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common',
		'../',

		# Allow MaterialSystem sources to see shader API headers.
		'shaderapidx9',
		'shaderapidx11'
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'vstdlib',
		'mathlib',
		'bitmap',
		'shaderlib',
		'vtf'
	]

	# DX11 backend is compiled into materialsystem.dll itself.
	# Therefore these libraries must be linked here, not only by shaderapidx11.
	if bld.env.DEST_OS == 'win32' and not bld.env.GL:
		libs += [
			'D3D11',
			'DXGI',
			'D3DCompiler'
		]

	install_path = bld.env.LIBDIR

	bld.shlib(
		source=source,
		target=PROJECT_NAME,
		name=PROJECT_NAME,
		features='c cxx',
		includes=includes,
		defines=defines,
		use=libs,
		install_path=install_path,
		subsystem=bld.env.MSVC_SUBSYSTEM,
		idx=bld.get_taskgen_count()
	)